[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  HUGO_VERSION = "0.71.1"

[context.deploy-preview]
  command = "npm install && npm run deploy"

[context.branch-deploy]
  command = "npm install && npm run deploy:branch"

[[headers]]
  for = "/index.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"