name = "Jamstack Themes"
license = "MIT"
description = "A list of Themes and Starters for Jamstack Sites."
min_version = "0.71.1"

[author]
  name = "Jamstack Themes"
  homepage = "https://www.jamstackthemes.dev"